# Generated by Django 5.1.6 on 2025-04-09 19:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0009_remove_profile_user_profile_profile_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('FOOD', '喂药'), ('MEDICINE', '看护'), ('DIET', '做饭'), ('CLEANING', '打扫'), ('TRANSPORT', '代取'), ('DELIVERYGET', '代送'), ('DELIVERYBUY', '代购'), ('OTHERS', '其他')], max_length=20, verbose_name='服务类型')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('IN_PROGRESS', '进行中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='状态')),
                ('service_time', models.DateTimeField(verbose_name='服务时间')),
                ('address', models.TextField(verbose_name='详细地址')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_provided', to='user_profile.userprofile', verbose_name='护工')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_received', to='user_profile.userprofile', verbose_name='被服务人')),
            ],
            options={
                'verbose_name': '服务',
                'verbose_name_plural': '服务管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
