# Generated by Django 5.1.6 on 2025-04-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='article/covers/', verbose_name='封面图'),
        ),
    ]
