# Generated by Django 5.1.6 on 2025-04-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_cover'),
        ('user_profile', '0009_remove_profile_user_profile_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_articles', to='user_profile.userprofile', verbose_name='点赞用户'),
        ),
        migrations.AddField(
            model_name='article',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
