# Generated by Django 4.2.7 on 2025-04-12 14:57

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='待填写', max_length=50, verbose_name='昵称')),
                ('avatar_file', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像文件')),
                ('avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像路径')),
                ('health_id', models.CharField(default='待填写', max_length=20, verbose_name='健康ID卡号')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('blood_pressure', models.CharField(default='待填写', max_length=20, verbose_name='血压')),
                ('blood_sugar', models.CharField(default='待填写', max_length=20, verbose_name='血糖')),
                ('blood_oxygen', models.CharField(default='待填写', max_length=20, verbose_name='血氧')),
                ('temperature', models.CharField(default='待填写', max_length=20, verbose_name='体温')),
                ('weight', models.CharField(default='待填写', max_length=20, verbose_name='体重')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', ckeditor.fields.RichTextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '个人档案',
                'verbose_name_plural': '个人档案',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='日程标题')),
                ('reminder_time', models.DateTimeField(verbose_name='提醒时间')),
                ('content', models.TextField(verbose_name='提醒内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_schedules', to='user_profile.userprofile', verbose_name='用户资料')),
            ],
            options={
                'verbose_name': '健康日程',
                'verbose_name_plural': '健康日程',
                'ordering': ['-reminder_time'],
            },
        ),
        migrations.CreateModel(
            name='CardPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_package', to='user_profile.userprofile', verbose_name='用户资料')),
            ],
            options={
                'verbose_name': '卡包',
                'verbose_name_plural': '卡包',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='卡名')),
                ('card_type', models.CharField(choices=[('ID', '身份证'), ('BANK', '银行卡'), ('MEMBER', '会员卡'), ('OTHER', '其他')], max_length=20, verbose_name='卡类型')),
                ('number', models.CharField(max_length=50, verbose_name='卡号')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('card_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='user_profile.cardpackage', verbose_name='所属卡包')),
            ],
            options={
                'verbose_name': '卡片',
                'verbose_name_plural': '卡片',
            },
        ),
        migrations.CreateModel(
            name='Guardianship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=20, verbose_name='监护关系称呼')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardianships_as_guardian', to='user_profile.userprofile', verbose_name='监护人')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardianships_as_ward', to='user_profile.userprofile', verbose_name='被监护人')),
            ],
            options={
                'verbose_name': '监护关系',
                'verbose_name_plural': '监护关系',
                'unique_together': {('guardian', 'ward')},
            },
        ),
    ]
