# Generated by Django 5.1.6 on 2025-03-01 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('avatar', models.ImageField(upload_to='avatars/', verbose_name='头像')),
                ('health_id', models.CharField(max_length=20, verbose_name='健康ID卡号')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('blood_pressure', models.CharField(max_length=20, verbose_name='血压')),
                ('blood_sugar', models.CharField(max_length=20, verbose_name='血糖')),
                ('blood_oxygen', models.CharField(max_length=20, verbose_name='血氧')),
                ('temperature', models.CharField(max_length=20, verbose_name='体温')),
                ('weight', models.CharField(max_length=20, verbose_name='体重')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='用户组')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
