# Generated by Django 5.1.6 on 2025-03-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='blood_oxygen',
            field=models.CharField(default='待填写', max_length=20, verbose_name='血氧'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='blood_pressure',
            field=models.CharField(default='待填写', max_length=20, verbose_name='血压'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='blood_sugar',
            field=models.CharField(default='待填写', max_length=20, verbose_name='血糖'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='health_id',
            field=models.CharField(default='待填写', max_length=20, verbose_name='健康ID卡号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='待填写', max_length=50, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='temperature',
            field=models.CharField(default='待填写', max_length=20, verbose_name='体温'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.CharField(default='待填写', max_length=20, verbose_name='体重'),
        ),
    ]
