# Generated by Django 5.1.6 on 2025-03-01 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='group',
        ),
        migrations.CreateModel(
            name='CardPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_package', to='user_profile.userprofile')),
            ],
            options={
                'verbose_name': '卡包',
                'verbose_name_plural': '卡包',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='卡名')),
                ('card_type', models.CharField(choices=[('ID', '身份证'), ('BANK', '银行卡'), ('MEMBER', '会员卡'), ('OTHER', '其他')], max_length=20, verbose_name='卡类型')),
                ('number', models.CharField(max_length=50, verbose_name='卡号')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('card_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='user_profile.cardpackage')),
            ],
            options={
                'verbose_name': '卡片',
                'verbose_name_plural': '卡片',
            },
        ),
    ]
