# Generated by Django 5.1.6 on 2025-03-01 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_userprofile_group_cardpackage_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardianship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=20, verbose_name='称呼')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to=settings.AUTH_USER_MODEL, verbose_name='监护人')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='user_profile.userprofile', verbose_name='被监护人')),
            ],
            options={
                'verbose_name': '监护关系',
                'verbose_name_plural': '监护关系',
                'unique_together': {('guardian', 'ward')},
            },
        ),
    ]
