# Generated by Django 5.1.6 on 2025-03-01 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_guardianship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpackage',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_package', to='user_profile.userprofile', verbose_name='用户资料'),
        ),
        migrations.AlterField(
            model_name='guardianship',
            name='relationship',
            field=models.CharField(max_length=20, verbose_name='监护关系称呼'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='HealthSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='日程标题')),
                ('content', models.TextField(verbose_name='日程内容')),
                ('reminder_time', models.DateTimeField(verbose_name='提醒时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='user_profile.userprofile', verbose_name='用户资料')),
            ],
            options={
                'verbose_name': '健康日程',
                'verbose_name_plural': '健康日程',
                'ordering': ['reminder_time'],
            },
        ),
    ]
