# Generated by Django 5.1.6 on 2025-03-01 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_cardpackage_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='user_profile.cardpackage', verbose_name='所属卡包'),
        ),
    ]
