# Generated by Django 5.1.6 on 2025-04-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_card_card_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianship',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardianships_as_guardian', to='user_profile.userprofile', verbose_name='监护人'),
        ),
        migrations.AlterField(
            model_name='guardianship',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardianships_as_ward', to='user_profile.userprofile', verbose_name='被监护人'),
        ),
    ]
