# Generated by Django 5.1.6 on 2025-04-08 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_guardianship_guardian_alter_guardianship_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='user_profile.userprofile', verbose_name='用户资料')),
            ],
            options={
                'verbose_name': '个人档案',
                'verbose_name_plural': '个人档案',
                'ordering': ['-created_at'],
            },
        ),
    ]
