# Generated by Django 5.1.6 on 2025-04-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_remove_profile_user_profile_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='头像'),
        ),
    ]
