# Generated by Django 5.1.6 on 2025-04-10 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_userprofile_avatar_file_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthschedule',
            options={'ordering': ['-reminder_time'], 'verbose_name': '健康日程', 'verbose_name_plural': '健康日程'},
        ),
        migrations.AlterField(
            model_name='healthschedule',
            name='content',
            field=models.TextField(verbose_name='提醒内容'),
        ),
        migrations.AlterField(
            model_name='healthschedule',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_schedules', to='user_profile.userprofile', verbose_name='用户资料'),
        ),
    ]
